[DEFAULT_CARDINAL_CONFIG]
    language = "en" # Cardinal's language (logs, etc.)


    github_api_page_url = "https://api.github.com/repos/Shiro-Okamoto/CardinalExtended" # Where to check for updates
    check_for_updates = true # Automatically check for new releases
    check_for_updates_delay = 600 # Delay between checks (in seconds)
    auto_update = false # Automatically update, if any new release is found (will also fully restart program)
    install_prereleases = false # Update to "prerelease" versions


    [DEFAULT_CARDINAL_CONFIG.plugins]
        load_all_plugins = false
        trusted_plugins = [] # If load_all_plugins = false, load only these plugins


    [DEFAULT_CARDINAL_CONFIG.proxy]
        enable = false # Use proxy for FunPay requests

        ip = ""
        port = ""
        login = ""
        password = ""

        check = false # Check proxy


    [DEFAULT_CARDINAL_CONFIG.FunPay]
        golden_key = "" # Session token FunPay
        user_agent = "" # Browser user-agent


        oldMsgGetMode = false

        keepSentMessagesUnread = false


    [DEFAULT_CARDINAL_CONFIG.Other]
        requestsDelay = 4 # FunPay runner's requests delay


        watermark = "🤖" # Watermark on bot's FunPay messages