[LOGGER]
    version = 1


    [LOGGER."formatters"]
        [LOGGER."formatters".console_formatter]
            "()" = "Utils.logger.ColoredFormatter"


        [LOGGER."formatters".file_formatter]
            "()" = "Utils.logger.FileFormatter"


    [LOGGER.handlers]
        [LOGGER.handlers.console_handler]
            class = "logging.StreamHandler"
            level = "INFO"
            formatter = "console_formatter"


        [LOGGER.handlers.file_handler]
            class = "logging.handlers.TimedRotatingFileHandler"
            level = "DEBUG"
            when = "midnight"
            formatter = "file_formatter"
            filename = "logs/log.log"
            backupCount = 25
            encoding = "utf-8"


    [LOGGER.loggers]
        [LOGGER.loggers.main]
            handlers = [
                "console_handler",
                "file_handler",
            ]
            level = "DEBUG"
            propogate = "True"


        [LOGGER.loggers.FunPayAPI]
            handlers = [
                "console_handler",
                "file_handler",
            ]
            level = "DEBUG"
            propogate = "True"


        [LOGGER.loggers.CardinalManager]
            handlers = [
                "console_handler",
                "file_handler",
            ]
            level = "DEBUG"
            propogate = "True"


        [LOGGER.loggers.C_EXT]
            handlers = [
                "console_handler",
                "file_handler",
            ]
            level = "DEBUG"
            propogate = "True"


        [LOGGER.loggers.Localizer]
            handlers = [
                "console_handler",
                "file_handler",
            ]
            level = "WARNING"
            propogate = "True"


        [LOGGER.loggers.plugins]
            handlers = [
                "console_handler",
                "file_handler",
            ]
            level = "DEBUG"
            propogate = "True"